services:
  mc:
    image: itzg/minecraft-server
    container_name: pixelparadise
    ports:
      # expose the Minecraft server port outside of container
      - "25565:25565"
    environment:
      # REQUIRED for all types
      EULA: "TRUE"
      # Set server type (vs the default of vanilla)
      TYPE: FORGE
      DEBUG: "true"
      VERSION: "1.20.1"
      FORGE_VERSION: "47.3.0"
      # REMOVE_OLD_MODS: "TRUE"
    volumes:
      - ./.minecraft_data:/data
      - ./mods:/mods:ro
      - ./config:/config
